#define MainDlg                     100
#define MainDlgCards                101
#define MainDlgKeep1                102
#define MainDlgKeep2                103
#define MainDlgKeep3                104
#define MainDlgKeep4                105
#define MainDlgKeep5                106
#define MainDlgAction1              107
#define MainDlgAction2              108
#define MainDlgAction3              109
#define MainDlgAction4              110
#define MainDlgAction5              111
#define MainDlgBet                  112
#define MainDlgBet5                 113
#define MainDlgAdvice               114
#define MainDlgOdds                 115
#define MainDlgBank                 116
#define MainDlgPayoutTable      117

#define MainFrame           1000
#define MainGame            1100
#define MainGameNew         1110
#define MainGameSelect          1120
#define MainGameExit            1190

#define MainHelp                1900
#define MainHelpIndex           1910
#define MainHelpAbout           1990

#define AppName                 2000
#define Version                 2001
#define BetTitle                    2002
#define BankText                2003
#define Keep                    2004
#define Discard                 2005
#define MainDlgHandTable            118
#define MainDlgHandValue            119
#define AboutDlg                    200
#define AboutDlgIcon                201
#define MainPayout              300

#define MainHelpTable   3000
#define MainHelpSubtable    3100
#define MainExtHelp        4000
