#define MainDlg                     100
#define MainFrame               1000
#define MainGame                    1100
#define MainGameNew             1110
#define MainGameAdd100              1120
#define MainGameCashOut             1130
#define MainGameExit                1190
#define MainOptions                 1200
#define MainOptionsSound            1210
#define MainSoundOn                 1211
#define MainSoundOff                1212
#define MainOptionsRules            1230
#define MainOptionsLang             1240
#define MainLang0                   1241
#define MainLang1                   1242
#define MainLang2                   1243
#define MainLang3                   1244
#define MainLang4                   1245
#define MainLang5                   1246
#define MainOptionsFrame            221
#define MainOptionsSave             1260
#define MainHelp                    1300
#define MainHelpGeneral             1301
#define MainHelpIndex               1302
#define MainHelpOnHelp              1303
#define MainHelpAbout               1399
#define MainHit                     1800
#define MainStand                   1810
#define MainDouble                  1820
#define MainSplit                   1830
#define MainDeal                    1840
#define MainWager                   1850
#define MainAdvice                  1860
#define MainInsurance               1811

#define PMT_BASE        900
#define NUMPROMPTS                  17
#define PMT_APPNAME                 0
#define PMT_VERSION                 1
#define PMT_NODECK                  2
#define PMT_NODECK_TITLE            3
#define PMT_BLACKJACK               4
#define PMT_BUST                    5
#define PMT_HIT                     6
#define PMT_STAND                   7
#define PMT_DOUBLE                  8
#define PMT_SPLIT                   9
#define PMT_DEAL                    10
#define PMT_ADVICE                  11
#define PMT_BANK                    12
#define PMT_PUSH                    13
#define PMT_LOSE                    14
#define PMT_WIN                     15
#define PMT_INSURANCE               16

#define SettingsDlg                 300
#define SettingsDlgResplit          301
#define SettingsDlgSoft17           302
#define SettingsDlgDouble1011       303
#define SettingsDlgNumDecks         304
#define SettingsDlgNumLabel         305
#define AboutDlg                    434

#define CHIP_INDEX                  4000
#define Chip5Bitmap                 4000

#define HID_MAIN                    432
#define HID_SUBTABLE                433
#define HID_GENERAL                 1
#define HID_PLAYING                 2
#define HID_RULES                   3
#define HID_MENUS                   4
#define HID_ABOUT                   5
