# makefile
# Created by IBM WorkFrame/2 MakeMake at 19:44:37 on 8 Feb 1999
#
# The actions included in this make file are:
#  Compile::C++ Compiler
#  Link::Linker
#  Bind::Resource Bind
#  Compile::Resource Compiler

.SUFFIXES:

.SUFFIXES: \
    .C .RC .obj .res 

.C.obj:
    @echo " Compile::C++ Compiler "
    icc.exe /O /Ge- /G5 /C %s

{G:\Programming\Programs\C\CGT\MultiPoker\BonusDeluxe}.C.obj:
    @echo " Compile::C++ Compiler "
    icc.exe /O /Ge- /G5 /C %s

.RC.res:
    @echo " Compile::Resource Compiler "
    rc.exe -r %s %|fF.RES

{G:\Programming\Programs\C\CGT\MultiPoker\BonusDeluxe}.RC.res:
    @echo " Compile::Resource Compiler "
    rc.exe -r %s %|fF.RES

all: \
    .\Bonus.DLL

.\Bonus.DLL: \
    .\Bonus.obj \
    .\Bonus.res \
    {$(LIB)}Bonus.DEF
    @echo " Link::Linker "
    @echo " Bind::Resource Bind "
    icc.exe @<<
     /FeBonus.DLL 
     Bonus.DEF
     .\Bonus.obj
<<
    rc.exe .\Bonus.res Bonus.DLL

.\Bonus.obj: \
    G:\Programming\Programs\C\CGT\MultiPoker\BonusDeluxe\Bonus.C \
    ..\MPokerDLL.H \
    {G:\Programming\Programs\C\CGT\MultiPoker\BonusDeluxe;$(INCLUDE);}Bonus.H

.\Bonus.res: \
    G:\Programming\Programs\C\CGT\MultiPoker\BonusDeluxe\Bonus.RC \
    {G:\Programming\Programs\C\CGT\MultiPoker\BonusDeluxe;$(INCLUDE)}Bonus.H \
    ..\MPokerDLL.H
