/************************************************************************
 *
 * File: CaribbeanStudRC.H
 *
 * Defines resource IDs.
 *
 ************************************************************************/
#define MainFrame   0x1000
#define MainGame    0x1100
#define MainGameNew     0x1110
#define MainGameExit        0x11F0
#define MainHelp            0x1F00
#define MainHelpIndex       0x1F10
#define MainHelpAbout       0x1FF0

#define PROMPT_BASE     0x0100
#define PMT_APPNAME                 0
#define PMT_VERSION                 1
#define PMT_ANTETITLE               2
#define PMT_BETTITLE                3
#define PMT_DEALERNAME              4
#define PMT_FOLD                    5
#define PMT_BET                         6
#define PMT_RESETSTAT       7
#define PMT_RESETSTATTITLE          8
#define PMT_LAST                    8
#define HAND_BASE                   0x0110

#define MainDlg                         100
#define MainDlgDealerHand           101
#define MainDlgPlayerHand           102
#define MainDlgDealerName           103
#define MainDlgJackpot              104
#define MainDlgBetField                  105
#define MainDlgBet                  106
#define MainDlgAnte                 107
#define MainDlgFold                 108

#define BitmapBet               200
#define BitmapAnte              201
#define BitmapEmpty             202
#define BitmapProgEmpty           203
#define BitmapProgFull            204
#define MainDlgProgSlot             110
#define MainDlgProgressive          111
#define MainDlgAnteSpin             109
#define MainDlgBank                 112
#define MainDlgProgAuto             113
#define MainDlgAddMoney             114
#define MainDlgHelp                 115
#define MainDlgAdvice               116
#define MainDlgAdviceText           117
#define MainDlgPlayerHandValue      118
#define MainDlgDealerHandValue      119
#define MainDlgDealerHas            120
#define MainDlgPlayerPaid           121
#define MainDlgPlayerPayout         122
#define MainDlgProgPays             123
#define MainDlgProgPayout           124
#define MainDlgBankText             125
#define MainDlgJackpotText          126
#define MainDlgExit                 127
#define StatsDlg                    300
#define StatsDlgReset               301
#define MainDlgStats                128
#define StatsDlgHand0               302
#define MainDlgCashOut              129
#define StatsDlgTotal               313
#define StatsDlgWin                 314
#define StatsDlgLose                315
#define StatsDlgFold                316
#define StatsDlgDealerFold          317
#define StatsDlgMoneyIn             318
#define StatsDlgMoneyOut            319
#define StatsDlgProg                320
#define StatsDlgProgPayout          321
